### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by drew-wallace** [formulahendry/vscode-auto-rename-tag#1]
I have the extention installed and added
`"auto-rename-tag.activationOnLanguage": [
        "html",
        "xml",
        "php"
    ]`
to my settings but it's not working

**Comment by formulahendry** [comment]
@drew-wallace Thanks for reporting the issue. Could you please provide more details? You mean the function is not working in [ "html", "xml", "php" ] language or the function is activated in languages other than [ "html", "xml", "php" ]?

**Comment by drew-wallace** [comment]
It's not working in [ "html", "xml", "php" ]

**Comment by formulahendry** [comment]
Which file type are you working on? Have you tried a html file just having content ```<div></div>``` and updated the tag name to see whether it works?

**Comment by drew-wallace** [comment]
PHP with the syntax set to HTML. I just tried an HTML file with HTML syntax and a `<div></div>` and it didn't work.

**Comment by drew-wallace** [comment]
OS X 10.11.3 and Windows 10
Both running VS Code 1.2.1

**Comment by formulahendry** [comment]
I'm also using Win10 and running VS Code 1.2.1 but it works. Could you let me know whether you have installed any other extensions? Maybe they have conflicts in some API. And could you try this [Auto Close Tag extension](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-close-tag) to see whether it works? Auto Close Tag has similar code logic with Auto Rename Tag. If it does not work as well. it is more likely there are conflicts with other extensions.

**Comment by drew-wallace** [comment]
Auto Close works for me... Interesting. I'll give you a list of my extensions when I get home.

**Comment by drew-wallace** [comment]
List of extensions:
file peek
html snippets
select line
handlebars
git history
***auto rename tab
***auto file name
Encode Decode
goto last edit
open
trailing spaces
multi clip
eval
lodash snippets
gitflow
gitblame
change case
javascript snippets

**Comment by drew-wallace** [comment]
After updating to VS Code 1.3.0 and I see it working half the time. Ending tags work most of the time, beginning tags don't always work either. I think having a chain of elements together on the same line may be part of why it's not working.

**Comment by dbettini** [comment]
Not working for me either. El Capitan, 1.3.0. No HTML extension except for [this](https://github.com/Zignd/HTML-CSS-Class-Completion), but I tried removing it and it still didn't work.

**Comment by formulahendry** [comment]
@drew-wallace Thanks for the update! Could you please provide scenarios when it is not working? Currently, one of the known issues is like ```<div><a href="http://www.example.com"></div>``` when there are single tag(s) between paired opening and closing tags. The ```div``` tag will not be updated correctly. I have plan to fix this issue.

@dbettini The extension is not working all the time or in some scenarios?

**Comment by dbettini** [comment]
@formulahendry not working at all, unfortunately. Removing/adding one character at a time or the entire word, always the same result. Tried it on closing and ending tags.

**Comment by formulahendry** [comment]
@dbettini Have you tried a html file just having content ```<div></div>``` and removed/added one character of the tag name to see whether it works?

**Comment by formulahendry** [comment]
@drew-wallace @dbettini An update for you. I have released new version 0.0.3 to fix some bugs. Not sure these fixes would be helpful to your cases. You could have a try and let me know if anything gets better.

**Comment by dbettini** [comment]
@formulahendry It works for me now. Thanks!

**Comment by drew-wallace** [comment]
Now works for me too!

**Comment by formulahendry** [comment]
Great!
