### ISSUE TITLE
Not working with VSCode 1.7. 

### ISSUE THREAD

**Issue by michaeljota** [formulahendry/vscode-auto-rename-tag#10]
I don't know why, but with the recent update it stop working. When I rename a tag, the closing tag it's not longer renamed too.

**Comment by formulahendry** [comment]
Hi @michaeljota , it works normally on my VS Code 1.7.1. Could you please select `Help> Toggle Developer Tools` from the top menu to see if there is any error message in the console?

**Comment by michaeljota** [comment]
This is working now.
