### ISSUE TITLE
Not work when using OPTION+DELETE (or CTRL+BACKSPACE)

### ISSUE THREAD

**Issue by nonoroazoro** [formulahendry/vscode-auto-rename-tag#12]
Ext Version: 0.0.8
VSCode Version: 1.7.1
OS: Mac

When I try to delete the whole tag by `option+delete` **right after I modified** the tag, the auto-rename will stop work.

![auto-rename-tag-issue](https://cloud.githubusercontent.com/assets/383132/20167591/69b9f078-a757-11e6-8514-a56c91438161.gif)

**Comment by formulahendry** [comment]
Thanks @nonoroazoro for your GIF of the repro steps! I will investigate and try to fix it.

**Comment by nonoroazoro** [comment]
@formulahendry You're welcome 😸!

**Comment by formulahendry** [comment]
Hi @nonoroazoro , this issue has been fixed. Please install the latest version and have a try.

**Comment by nonoroazoro** [comment]
@formulahendry Great!!!
