### ISSUE TITLE
causes need for extra undo keystrokes

### ISSUE THREAD

**Issue by geddski** [formulahendry/vscode-auto-rename-tag#13]
changing a tagname and then hitting cmd+z to undo now requires hitting undo many extra times (once per letter of the tag). Is there a way for this plugin to make it's changes in a way that don't cause any history entries?

**Comment by formulahendry** [comment]
Hi @geddski , I am afraid that it may not be possible to make that. I will try to investigate whether there is a way to make that.

**Comment by Deilan** [comment]
#21

**Comment by formulahendry** [comment]
Hi @geddski , this issue has been fixed now. Please install the the latest version and have a try!

**Comment by geddski** [comment]
Awesome thanks!!
