### ISSUE TITLE
When moving rows with "alt+up/down" it renames tags in the process

### ISSUE THREAD

**Issue by andi91** [formulahendry/vscode-auto-rename-tag#14]
When moving lines up or down using the "alt+up/down" shortcut, it renames tags in the lines it moves over automatically. This makes it impossible to use this extension for me, because I tend to use this shortcut a lot, Otherwise great extension!

I'm using VSCode version 1.7.1

**Comment by formulahendry** [comment]
Could you please share to code snippet for the repro steps?

**Comment by andi91** [comment]
`<div class="a">
  <div>
    <p>
      <a>

      </a>
    </p>
  </div>
</div>`

Yeah I just noticed it doesn't happen all the time. Here's how I reproduced it: Place the caret behind the first 'p' in the <p> tag. Then use alt+up. The closing </p> tag then gets renamed to </div>. This happens when the caret moves into another tag. If you place the caret on the beginning of the line, it doesn't rename. Hope this helped you reproduce it!

**Comment by formulahendry** [comment]
Thanks for the detailed repro steps! I will have a look.

**Comment by formulahendry** [comment]
Hi @andi91 , this issue has been fixed. Please install the latest version and have a try.
