### ISSUE TITLE
Redo breaks when extension is enabled

### ISSUE THREAD

**Issue by Joead** [formulahendry/vscode-auto-rename-tag#15]
Thanks for providing this extension - very useful. However there's one issue that is stopping me using it: 

When a tag name is changed it breaks redo. i.e. undo the tag name change then try and redo it. The redo doesn't work and does't redo any upstream changes that you may have done after the tag renaming.

OSX 10.12.1
Code 1.7.2
Auto Rename Tag 0.0.8

**Comment by formulahendry** [comment]
Thanks @Joead for reporting it, I will investigate this issue.

**Comment by Deilan** [comment]
Looks the same as #21.

**Comment by Deilan** [comment]
#21

**Comment by formulahendry** [comment]
@Joead , this issue has been fixed now. Please install the the latest version and have a try!
