### ISSUE TITLE
Unexpected renaming

### ISSUE THREAD

**Issue by M-Yankov** [formulahendry/vscode-auto-rename-tag#17]
![gifbug](https://cloud.githubusercontent.com/assets/10440078/21568825/54f41e26-cec0-11e6-9004-f402cd758dfd.gif)

Using `Alt+↓` to swap current row causes unexpected renaming of HTML elements. 
Notice that the `div` is changed to `h2`

The action in VS Code is `editor.action.moveLinesDownAction`
VSCode : 
- version is 1.8.1
- Shell: 1.4.6
- Renderer: 53.0.2785.143
- Node: 6.5.0

OS: Windows 10x64

**Comment by formulahendry** [comment]
Hi @M-Yankov , this issue has been fixed. Please install the latest version and have a try.

**Comment by M-Yankov** [comment]
Thanks It works, Happy New Year 💥 🎉
