### ISSUE TITLE
fails when you backspace whole tag

### ISSUE THREAD

**Issue by mikescott8** [formulahendry/vscode-auto-rename-tag#2]
I had a div tag in a test file. I go to after the v in the opening tag and backspace three times to change to a p tag. after I backspaced the 'd' the closing tag kept the 'd' and then when I typed the 'p' the closing tag was out of synch.

**Comment by formulahendry** [comment]
Fix this issue in v0.0.3. Please install the v0.0.3 and have a try.Thanks for reporting it!
