### ISSUE TITLE
undo after rename tag

### ISSUE THREAD

**Issue by PYangDizzle** [formulahendry/vscode-auto-rename-tag#21]
I have read the issue note from the November 2016, which seemed to be the similar issue but not.

If I undo after renaming the tag, I lose all undo stacks and can only undo the last character of the tag.

If I change <police> to <polite> and then press ctrl+z, vscode will repeat back and forth between <polite> and <polit>

I installed the plugin today through vscode plugin installer

**Comment by formulahendry** [comment]
Seems like this strange behavior started from VS Code 1.9 (or an earlier version)...

**Comment by Deilan** [comment]
I also confirm that. Undoing changes becomes a mess. In my experience it occurs starting from at least v1.8.x.

Affects that much that I am considering removing the extension until it is fixed. =(

**Comment by Deilan** [comment]
#13

**Comment by Deilan** [comment]
#15

**Comment by xekri** [comment]
Confirmed and confused.

**Comment by martindederer** [comment]
The faulty behavior still exists in vs code 1.11.0.

**Comment by oshalygin** [comment]
I can take a look at this

**Comment by formulahendry** [comment]
Hi all, with a lot of investigation and debug work, I finally find that there is a VS Code API change which leads to this bug. 😢 Fortunately, we are able to fix it! 😃 I know all of you are waiting so long time for this fix! Please install the the latest version and have a try!
