### ISSUE TITLE
Make editor lag when edit single tag in jsx file.

### ISSUE THREAD

**Issue by suyuanhan** [formulahendry/vscode-auto-rename-tag#23]
I use vscode 1.9 both in windows7 and macos with jsx file,
and when I edit single tag like `<input />`
 or  `<img />` inside ,
add a className or other attribute,
it makes the vscode eidtor so lag.

**Comment by formulahendry** [comment]
Hi @suyuanhan , how large is your jsx file? Could you please share the jsx file so that I could try to reproduce it?

**Comment by suyuanhan** [comment]
Oh,I'm sorry to border you cause I not get this bug today.
I think you can close this issue now.If happen next time I'll show more detail code or operation.
And thanks ,this plugin save me a lot of time in work~~!
Sorry for wasted you time~

**Comment by formulahendry** [comment]
Never mind~
