### ISSUE TITLE
it cause a problem when type `<` in class binding exp in vue files

### ISSUE THREAD

**Issue by BboyAwey** [formulahendry/vscode-auto-rename-tag#28]
when type `<` in class binding exp in vue files, it cause an unknown problem in vscode and makes the typing after `<` very slow.

I've created an issue in vscode but found it is caused by auto-rename-tag:

https://github.com/Microsoft/vscode/issues/28686#issuecomment-308323572

**Comment by formulahendry** [comment]
Could you please check the CPU usage of VS Code?

**Comment by BboyAwey** [comment]
It's higher than normal, from 7 percent up to about 40 percent, but not higher more

**Comment by formulahendry** [comment]
Did you disable all other extensions and only enable Auto Rename Tag?

**Comment by BboyAwey** [comment]
yes, all the extension have been closed but it still cause the problem when I test it.
but it been a while and some of the extensions have updated so i think you can close this issue now and I cannot reappear the bug now.
if I meet it again i will create a new issue.
anyway, thank you for create this nice extension!
