### ISSUE TITLE
Selecting whole tag and changing doesn't change the matching tag

### ISSUE THREAD

**Issue by mikescott8** [formulahendry/vscode-auto-rename-tag#3]
if I select the whole text of a tag ie the text 'div' in a tag by double clicking the tag, and then type in a new tag, it doesn't update the matching tag.

if I highlight PART of a tag like 'one' in 'divone' and change it, then it does work.

**Comment by formulahendry** [comment]
Fix this issue in v0.0.3. Please install the v0.0.3 and have a try.Thanks for reporting it!
