### ISSUE TITLE
Implement multiple cursor support.

### ISSUE THREAD

**Issue by ravshansbox** [formulahendry/vscode-auto-rename-tag#37]
![20171026-122552](https://user-images.githubusercontent.com/1499188/32019034-434e22d2-b9e5-11e7-9583-dbfb7b77ec43.gif)

**Comment by asphub** [comment]
Multiple cursor is not supporting... 😟

Waiting for this feature..

**Comment by rienheuver** [comment]
Just ran into this problem on first usage of the extension, please fix this!

**Comment by tonivj5** [comment]
https://github.com/formulahendry/vscode-auto-rename-tag/pull/511 doesn't fixes this

**Comment by SimonSiefke** [comment]
@tonivj5 Do you have an example where it doesn't work? The code snippet in this issue its definitely working for me with multi-cursor.

![it-works](https://user-images.githubusercontent.com/23744935/80373288-2033ed00-8895-11ea-9387-9dace2186e33.gif)

**Comment by tonivj5** [comment]
@SimonSiefke It doesn't work if the multicursor is nested
```html
<a>
  <a></a>
</a>
``` 
![cursor](https://user-images.githubusercontent.com/7110786/80383593-12d22f00-88a4-11ea-8d41-40c54a364bfc.gif)

**Comment by SimonSiefke** [comment]
Great catch! Will try to improve on that.
