### ISSUE TITLE
Add support for Typescript

### ISSUE THREAD

**Issue by RyanMitchellWilson** [formulahendry/vscode-auto-rename-tag#39]
Would be great if this could work in TSX file too. I really like this extension keep up the good work.

**Comment by formulahendry** [comment]
Could you share the code snippet of your TSX?

**Comment by RyanMitchellWilson** [comment]
Sure, the JSX inside a TSX file is the exact same as it is in a JSX file, but here is a quick example:
```
<View style={{flex: 1}}>
  <Text>Example TSX (Same as JSX)</Text>
  <Image src={require('../../...')}/>
</View>
```

Let me know if this helps

**Comment by formulahendry** [comment]
It is working on my side. Could you disable all other extensions and try again?
![pic](https://user-images.githubusercontent.com/1050213/33161736-74a5ea4a-d060-11e7-9c9f-35152244d651.gif)

**Comment by RyanMitchellWilson** [comment]
Still not working. This works fine unless you have a file extension of tsx. For example `Home.tsx` instead of `Home.jsx`. Even if both files have the exact same code, this extension will only work for the jsx file not the tsx file

**Comment by formulahendry** [comment]
Also work using ***.tsx file. Could you disable all other extension and try again?

**Comment by RyanMitchellWilson** [comment]
It seems to only work with React-Native components. Whenever I try it on a View or a Text tag it works just fine, but if I try to use this with a custom component or a component from a different library it doesn't work.

**Comment by formulahendry** [comment]
Could you share the detailed code snippet?

**Comment by RyanMitchellWilson** [comment]
```
<View style={styles.columnMiddle}>
  <CustomTouchableOpacity
    delay={0}
    onPress={this.play}
    style={styles.playButton}>
    <IonIcon
      name={isPlaying ? 'md-pause' : 'md-play'}
      style={playIconStyle}/>
  </CustomTouchableOpacity>
</View>
```
It works just fine when I edit the view, but not when I edit the CustomTouchableOpacity. Seems to only work on react-native specific jsx tags and not custom components or components from libraries.

**Comment by formulahendry** [comment]
Got that. Duplicated with #19
