### ISSUE TITLE
Tags with dash  in name not getting auto renamed

### ISSUE THREAD

**Issue by dbettini** [formulahendry/vscode-auto-rename-tag#4]
Tags with dash in their name do not get autocompleted after the dash.

Example:
I want to rename `<div></div>` into `<company-header></company-header>`.
While typing 'company',   all is well. However, the dash doesn't get reflected to the closing tag, or any characters behind the dash. So I end up with `<company-header></company>`.

**Comment by formulahendry** [comment]
@dbettini This issue has been fixed in v0.0.4. Please install and have a try.

**Comment by dbettini** [comment]
Thanks, works like a charm.
