### ISSUE TITLE
Less-than sign breaks auto-rename

### ISSUE THREAD

**Issue by Zaczero** [formulahendry/vscode-auto-rename-tag#45]
This is really annoying when you use PHP code in your tags.

## Preview:
![](https://i.imgur.com/EAQS62l.gif)

## Code:
```HTML
<div title="<?php echo "FOO"?>">
</div>

<span title="<">
</span>
```

**Comment by konrad0349** [comment]
I have encountered this also. Along with a few other issues that I believe have already been reported.

Still, this is a good effort and I like the other extensions you have created. Keep up the good work.

Thanks
