### ISSUE TITLE
Can't rename multiline opening tag

### ISSUE THREAD

**Issue by numberokta** [formulahendry/vscode-auto-rename-tag#479]
It can't rename multiline opening tag in React Native JSX like this :

&lt;View
&nbsp;&nbsp;&nbsp;&nbsp;style={{flex: 1}}
&gt; 
&nbsp;&nbsp;&nbsp;&nbsp;&lt;Text&gt;Hello World!&lt;/Text&gt;
&lt;/View&gt;

**Comment by nitePhyyre** [comment]
This is also a problem for tags with a "-" in them. I'll be changing a "div" to a "v-row" or whatever. The closing tag stays as "v-".

**Comment by kodyn-s-kugis** [comment]
Experienced same issue with HTML with both multi-line editing or multi-cursor editing. Only the final selection that was made in the multi-selection would be recognised by auto-rename to change the closing tag. All other remaining tags wouldn't automatically adjust the closing tag.
