### ISSUE TITLE
Using delete key causes problems

### ISSUE THREAD

**Issue by willpower232** [formulahendry/vscode-auto-rename-tag#49]
Using the delete key instead of backspace causes weird behaviour

![unnesteddelete](https://user-images.githubusercontent.com/1619102/37148686-3b7c8002-22c3-11e8-838a-0f3b7512a051.gif)

Also if you do that in a nested table, it gets even worse (note the parent `<t>` tags)

![delete](https://user-images.githubusercontent.com/1619102/37148705-5145df78-22c3-11e8-9cf7-b100a15a2a94.gif)

Potentially related to https://github.com/formulahendry/vscode-auto-rename-tag/issues/12

**Comment by solid-pixel** [comment]
Yeah it's very annoying, I've had to stop using it :(

**Comment by willpower232** [comment]
Thanks @Zaczero !
