### ISSUE TITLE
编码是GBK莫名会变成 ‘锟侥革拷锟斤拷锟斤拷’

### ISSUE THREAD

**Issue by zykoikaze** [formulahendry/vscode-auto-rename-tag#52]
编码是GBK，中文汉字莫名会变成 ‘锟侥革拷锟斤拷锟斤拷’

**Comment by formulahendry** [comment]
Do you open issue in a right repo? It is repo of 'Auto Rename Tag' extension.

**Comment by zykoikaze** [comment]
这个是新的问题，不好意思，提的有些混乱，我会注意的：这个问题是.xsl文件本身编码是GBK的，我在设置里：
"[xsl]": {
        "files.encoding": "gbk"
    }
从线上把.xsl的代码拉下来后，就会变成'锟斤拷影'，这个怎么解决

**Comment by formulahendry** [comment]
这个问题和Auto Rename Tag这个插件有什么关系呢？

**Comment by zykoikaze** [comment]
和这个插件没关系，最近用没有遇到之前那种情况了。额，我是不是提错地方了，真抱歉！
