### ISSUE TITLE
Doesn't work with tags that start with $.

### ISSUE THREAD

**Issue by spacesuitdiver** [formulahendry/vscode-auto-rename-tag#528]
![2020-04-12 11-55-46 2020-04-12 11_56_18](https://user-images.githubusercontent.com/2807897/79074891-ac022280-7cb4-11ea-8641-390dc058169b.gif)

**Comment by icleolion** [comment]
Still an issue in 0.1.3.  

For reference I know the PR that led to much appreciated 0.1.2 release was loosely based on VS Code's HTML parser (https://github.com/formulahendry/vscode-auto-rename-tag/pull/511#issuecomment-595388110) which is capable of handling tags that start with $.
