### ISSUE TITLE
Support rename script and style tag in HTML files

### ISSUE THREAD

**Issue by humphreygao** [formulahendry/vscode-auto-rename-tag#542]
我试了下在HTML文件中不能同时重命名`script`的开关标签。

**Comment by humphreygao** [comment]
@SimonSiefke Thank you, but it seems that this issue is not fixed.

**Comment by SimonSiefke** [comment]
@humphreygao There is an [issue with the VSCode marketplace](https://github.com/microsoft/vscode/issues/98472) which causes VSCode to install a wrong version.

You can download v0.1.4 manually:
Step 1: Download [auto-rename-tag-0.1.4.zip](https://github.com/formulahendry/vscode-auto-rename-tag/files/4870960/auto-rename-tag-0.1.4.zip) and extract the zip
Step 2: In VSCode, open the Command Palette with <kbd>Ctrl+Shift+P</kbd> and type "Extensions: Install from vsix"
Step 3: Select the vsix and install

**Comment by humphreygao** [comment]
> @humphreygao There is an [issue with the VSCode marketplace](https://github.com/microsoft/vscode/issues/98472) which causes VSCode to install a wrong version.
> 
> You can download v0.1.4 manually:
> Step 1: Download [auto-rename-tag-0.1.4.zip](https://github.com/formulahendry/vscode-auto-rename-tag/files/4870960/auto-rename-tag-0.1.4.zip) and extract the zip
> Step 2: In VSCode, open the Command Palette with Ctrl+Shift+P and type "Extensions: Install from vsix"
> Step 3: Select the vsix and install

@SimonSiefke It works! :smiley:
