### ISSUE TITLE
Extension automatically modifies the react fragment syntax in vs code

### ISSUE THREAD

**Issue by kishoreio** [formulahendry/vscode-auto-rename-tag#543]
When i use react fragment and insert a tag inside it, for example section tag and inside the section when i nested a tag like h1, the extension automatically modifies the react fragment to the one that was nested inside the section tag.
![issue](https://user-images.githubusercontent.com/30261988/84235678-e3097e80-ab13-11ea-9215-700ad2954e8c.gif)

**This issue not only happens for section tag and h1 tag but whatever tag i use and inside that parent tag when i nest a child tag, this tag name is added to the enclosing react fragment.**

**Comment by SimonSiefke** [comment]
This is a duplicate of https://github.com/formulahendry/vscode-auto-rename-tag/issues/535  which has been fixed. But there is an [issue with the VSCode marketplace](https://github.com/microsoft/vscode/issues/98472) which causes VSCode to install a wrong version.

You can download v0.1.4 manually:
Step 1: Download [auto-rename-tag-0.1.4.zip](https://github.com/formulahendry/vscode-auto-rename-tag/files/4872248/auto-rename-tag-0.1.4.zip) and extract the zip
Step 2: In VSCode, open the Command Palette with Ctrl+Shift+P and type "Extensions: Install from vsix"
Step 3: Select the vsix and install

**Comment by kishoreio** [comment]
Ok
