### ISSUE TITLE
doesn't always work well with EJS

### ISSUE THREAD

**Issue by keenan137** [formulahendry/vscode-auto-rename-tag#568]
The h2 tag was p initially, when I renamed it I first removed the p (leaving "<>" and "</>"), and when I then placed <h2> on the opening tag, it did not automatically update the closing tag. When I tried typing in the closing tag manually (</h2>) it automatically added h2 in the EJS tag, the result is below:

<h2><h2%= camp.location %></h2>

**Comment by SimonSiefke** [comment]
I'm not quite sure what you mean. Could you wrap the code in your issue with triple backticks? For example

````
```html
<h1>hello world</h1>
```
````

gets rendered as

```html
<h1>hello world</h1>
```

**Comment by Tom4sBeltr4n** [comment]
He tried renaming a ```p``` tag to an ```h2``` by backspacing the p and adding h2. The tag was then left blank, and when he tried updating the opening tag (```<>``` -> ```<h2>``` )it didn't update on the closing tag. Solving this manually (adding ```</h2>```) ended in a new opening tag being created. ```<h2></h2>```
