### ISSUE TITLE
Publish to open-vsx.org?

### ISSUE THREAD

**Issue by hl2guide** [formulahendry/vscode-auto-rename-tag#590]
Please consider publishing this extension to: https://open-vsx.org/

So that users of VSCodium can use it too.

**Comment by quangv** [comment]
+1, wanted to use this awesome plugin with [gitpod.io](https://gitpod.io)

**Comment by quangv** [comment]
in my `.gitpod.yml` was able to install auto-rename-tag extension with:

```
vscode:
  extensions:
    - esbenp.prettier-vscode
    - eamodio.gitlens
    - https://github.com/formulahendry/vscode-auto-rename-tag/releases/download/0.1.0/auto-rename-tag-0.1.0.vsix
```
