### ISSUE TITLE
The extension seems to be creating high CPU usage on M1 Pro

### ISSUE THREAD

**Issue by panchi64** [formulahendry/vscode-auto-rename-tag#612]
Hi, just wanted to report that this specific extension seems to like hogging CPU resources at the moment

Here's an attached image confirming that this extension in specific is hogging the resources:
<img width="1681" alt="Screen Shot 2022-08-07 at 2 23 35 PM" src="https://user-images.githubusercontent.com/34542704/183309881-0932c80a-cafe-419f-9111-9105f3594c32.png">

**Comment by EGurney** [comment]
I had to disable this extension for this reason.  
It was causing my Macbook fan to be noisy, and the CPU usage to be very high the entire time I was working.

Disabled this extension and the Macbook is back to silent and chill.

**Comment by panchi64** [comment]
I believe this has been resolved with the newest release of VSCode. It seemed to be some underlying logic regarding Javascript processing on the editor.
