### ISSUE TITLE
Multiple Cursor support?

### ISSUE THREAD

**Issue by glenndevenish** [formulahendry/vscode-auto-rename-tag#63]
### Problem
Currently when renaming more than one tag using the [multiple cursor](https://stackoverflow.com/a/29953572) feature on VS Code, it only renames the _first tag to be selected_.

While trying to create a demonstration, I noticed that it doesn't like 'emptying' the tag (as in `<b>` to `<>` to `<strong>`, which is able to be done for only one tag). 
This is why you see `</bstrong>` in the first tag and `</>` in the last one.

It would be nice if it was to rename all tags selected, with the same tag name (so, if I select `<b>` and also `<span>`, it would only rename the highlighted tag or something).

### Example: 

Multiple tags to change:
![image](https://user-images.githubusercontent.com/31036664/42128913-f94812c4-7cad-11e8-958f-e4b1f80a8a62.png)

Only changes selected one:
![image](https://user-images.githubusercontent.com/31036664/42128932-2870a46c-7cae-11e8-8c30-16cf46107806.png)

**Comment by asphub** [comment]
Multiple cursor not supporting... 😟

Waiting for this feature

**Comment by formulahendry** [comment]
Duplicated with #37
