### ISSUE TITLE
Conflict with Emmet

### ISSUE THREAD

**Issue by geirsagberg** [formulahendry/vscode-auto-rename-tag#8]
Strange bug, doesn't happen every time, but almost:

1. In a html file, type `div` and press tab to expand
2. Press enter to create new line
3. Type e.g. `h2` and press tab
4. See that the closing tag of the `div` is renamed to `h2`

![vscode-bug](https://cloud.githubusercontent.com/assets/594564/17130486/083f6680-5319-11e6-94f5-fcae62defaaf.gif)

**Comment by formulahendry** [comment]
Hi @geirsagberg , this issue has been fixed. Please try the latest version.

**Comment by geirsagberg** [comment]
Looks great, thanks!
